/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoclinicadental;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class frmTratamientosOdontologicos extends javax.swing.JFrame {

    /**
     * Creates new form frmTratamientosOdontologicos
     */
    
    class_TratamientosDentDisponibles trat=new class_TratamientosDentDisponibles();
    ResultSet rst_lista=null;  
    DefaultListModel modelo=new DefaultListModel();
    public frmTratamientosOdontologicos() {
        initComponents();
        llenarlista();
        txtTratamiento.setFont(new java.awt.Font("Times New Roman", 0, 20)); 
        lblTemaTratamientos.setFont(new java.awt.Font("Times New Roman", 0, 20)); 
        lblTratamiento.setFont(new java.awt.Font("Times New Roman", 0, 20)); 
        lstTratamientos.setFont(new java.awt.Font("Times New Roman", 0, 20)); 
        btnAgregarTratamiento.setFont(new java.awt.Font("Times New Roman", 0, 20)); 
        btnAtrasTratamiento.setFont(new java.awt.Font("Times New Roman", 0, 20)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTemaTratamientos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTratamientos = new javax.swing.JList<>();
        lblTratamiento = new javax.swing.JLabel();
        txtTratamiento = new javax.swing.JTextField();
        btnAgregarTratamiento = new javax.swing.JButton();
        btnAtrasTratamiento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTemaTratamientos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTemaTratamientos.setForeground(java.awt.Color.red);
        lblTemaTratamientos.setText("TRATAMIENTOS ODONTOLOGICOS");
        getContentPane().add(lblTemaTratamientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 22, 324, 40));

        lstTratamientos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(lstTratamientos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 270, 240));

        lblTratamiento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTratamiento.setForeground(java.awt.Color.orange);
        lblTratamiento.setText("Añadir tratamiento:");
        getContentPane().add(lblTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 30));

        txtTratamiento.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTratamientoActionPerformed(evt);
            }
        });
        txtTratamiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTratamientoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 230, -1));

        btnAgregarTratamiento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAgregarTratamiento.setForeground(java.awt.Color.green);
        btnAgregarTratamiento.setText("AGREGAR");
        btnAgregarTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTratamientoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 398, -1, -1));

        btnAtrasTratamiento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAtrasTratamiento.setForeground(java.awt.Color.red);
        btnAtrasTratamiento.setText("ATRAS");
        btnAtrasTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasTratamientoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtrasTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 398, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fundo-azul.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTratamientoActionPerformed
        if(txtTratamiento.getText().length()>4){
            trat.insertar(txtTratamiento.getText());
            JOptionPane.showMessageDialog(this, "Nuevo tratamiento registrado con éxito");
        }else
            JOptionPane.showMessageDialog(this, "No hay un dato representativo del tratamiento");
        llenarlista();
    }//GEN-LAST:event_btnAgregarTratamientoActionPerformed

    private void btnAtrasTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasTratamientoActionPerformed
            frmMenuPrincipal menu=new frmMenuPrincipal();
            this.dispose();
            menu.setVisible(true);
    }//GEN-LAST:event_btnAtrasTratamientoActionPerformed

    private void txtTratamientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTratamientoKeyTyped
        if(txtTratamiento.getText().length()==100)
            evt.consume();
    }//GEN-LAST:event_txtTratamientoKeyTyped

    private void txtTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTratamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTratamientoActionPerformed

    private void llenarlista(){        
        try{
            modelo.removeAllElements();
            rst_lista=trat.ListaTratamientos();
            while (rst_lista.next()) 
                modelo.addElement(rst_lista.getString(1).toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
                modelo.addElement("Error");
        }
        lstTratamientos.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTratamientosOdontologicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTratamientosOdontologicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTratamientosOdontologicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTratamientosOdontologicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTratamientosOdontologicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarTratamiento;
    private javax.swing.JButton btnAtrasTratamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTemaTratamientos;
    private javax.swing.JLabel lblTratamiento;
    private javax.swing.JList<String> lstTratamientos;
    private javax.swing.JTextField txtTratamiento;
    // End of variables declaration//GEN-END:variables
}
